/**
 * CODM Text Effect
 */

const axios = require('axios');
const config = require('../../config');

module.exports = {
  name: 'codm',
  aliases: ['callofduty', 'callofdutymobile'],
  category: 'textmaker',
  description: 'Create a Call of Duty Mobile text effect',
  usage: '.codm <text>',

  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;

      if (!text) {
        return await sock.sendMessage(chatId, {
          text: 'Please provide text to generate\nExample: .codm Nick'
        }, { quoted: msg });
      }

      const imageResponse = await axios.get('https://loremflickr.com/1024/1024/callofduty,mobile?lock=' + Date.now(), {
        responseType: 'arraybuffer',
        timeout: 120000,
      });

      await sock.sendMessage(chatId, {
        image: Buffer.from(imageResponse.data),
        caption: `🎮 CODM\n\n📝 ${text}\n\nGENERATED BY ${config.botName}`
      }, { quoted: msg });
    } catch (error) {
      console.error('Error in codm command:', error);
      await sock.sendMessage(msg.key.remoteJid, {
        text: `Error: ${error.message}`
      }, { quoted: msg });
    }
  }
};
