/**
 * eFootball Text Effect
 */

const axios = require('axios');
const config = require('../../config');

module.exports = {
  name: 'efootball',
  aliases: ['efoot', 'pes'],
  category: 'textmaker',
  description: 'Create an eFootball text effect',
  usage: '.efootball <text>',

  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;

      if (!text) {
        return await sock.sendMessage(chatId, {
          text: 'Please provide text to generate\nExample: .efootball Nick'
        }, { quoted: msg });
      }

      const imageResponse = await axios.get('https://loremflickr.com/1024/1024/football,stadium?lock=' + Date.now(), {
        responseType: 'arraybuffer',
        timeout: 120000,
      });

      await sock.sendMessage(chatId, {
        image: Buffer.from(imageResponse.data),
        caption: `⚽ eFOOTBALL\n\n📝 ${text}\n\nGENERATED BY ${config.botName}`
      }, { quoted: msg });
    } catch (error) {
      console.error('Error in efootball command:', error);
      await sock.sendMessage(msg.key.remoteJid, {
        text: `Error: ${error.message}`
      }, { quoted: msg });
    }
  }
};
