/**
 * PUBG Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'pubg',
  aliases: ['pubgmobile'],
  category: 'textmaker',
  description: 'Create a PUBG Mobile text effect',
  usage: '.pubg <text>',

  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;

      if (!text) {
        return await sock.sendMessage(chatId, {
          text: 'Please provide text to generate\nExample: .pubg Nick'
        }, { quoted: msg });
      }

      const result = await mumaker.ephoto('https://en.ephoto360.com/create-pubg-mobile-logo-by-mastering-360.html', text);

      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }

      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `🎮 PUBG MOBILE\n\nGENERATED BY ${config.botName}`
      }, { quoted: msg });
    } catch (error) {
      console.error('Error in pubg command:', error);
      await sock.sendMessage(msg.key.remoteJid, {
        text: `Error: ${error.message}`
      }, { quoted: msg });
    }
  }
};
